### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by wipfal** [disk91/itsdk-example-murata-lora#1]
cannot compile following command is showing:

Core/Src/sysmem.o: In function `_sbrk':
sysmem.c:(.text._sbrk+0x30): undefined reference to `_Min_Stack_Size'
sysmem.c:(.text._sbrk+0x34): undefined reference to `_estack'
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:95: itsdk-example-murata-lora.elf] Error 1
make: *** [makefile:88: all] Error 2
"make -j7 all" terminated with exit code 2. Build might be incomplete.

**Comment by disk91** [comment]
This looks really strange ... Are you using CubeIDE to compile ?
Can you tell me if you made anything different than what is documented ?

**Comment by disk91** [comment]
No compilation issue on my side

**Comment by 73jn** [comment]
I have the same error :(
I use STM32CubeIDE Version: 1.4.0

10:56:40 **** Incremental Build of configuration Release for project itsdk-example-murata-lora ****
make -j8 all 
touch "C:\Users\jeann\STM32CubeIDE\workspace_1.4.0\itsdk-example-murata-lora\stm32-it-sdk\Src\it_sdk\console\console.c"
 
arm-none-eabi-gcc "../stm32-it-sdk/Src/it_sdk/console/console.c" -mcpu=cortex-m0plus -std=gnu11 -DUSE_HAL_DRIVER -DSTM32L072xx -c -I../Core/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc -I../Drivers/STM32L0xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32L0xx/Include -I../Drivers/CMSIS/Include -I"C:/Users/jeann/STM32CubeIDE/workspace_1.4.0/itsdk-example-murata-lora/stm32-it-sdk/Inc" -Os -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"stm32-it-sdk/Src/it_sdk/console/console.d" -MT"stm32-it-sdk/Src/it_sdk/console/console.o" --specs=nano.specs -mfloat-abi=soft -mthumb -o "stm32-it-sdk/Src/it_sdk/console/console.o"
arm-none-eabi-gcc -o "itsdk-example-murata-lora.elf" @"objects.list"   -mcpu=cortex-m0plus --specs=nosys.specs -Wl,-Map="itsdk-example-murata-lora.map" -Wl,--gc-sections -static --specs=nano.specs -mfloat-abi=soft -mthumb -Wl,--start-group -lc -lm -Wl,--end-group
Core/Src/sysmem.o: In function `_sbrk':
sysmem.c:(.text._sbrk+0x30): undefined reference to `_Min_Stack_Size'
sysmem.c:(.text._sbrk+0x34): undefined reference to `_estack'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [makefile:95: itsdk-example-murata-lora.elf] Error 1
make: *** [makefile:88: all] Error 2
"make -j8 all" terminated with exit code 2. Build might be incomplete.

10:56:44 Build Failed. 2 errors, 0 warnings. (took 3s.649ms)

**Comment by disk91** [comment]
It is possible that the project LD path was not correct even if obtained from parameters
I had this experience on the sigfox example.
You may be able to change the project LD filepath in the project build property, just by replacing the string chain with the ldscript directly.
I'll check that and make an update. Let me know if this solved your issue (and if you understood anything on my poor explanation)

**Comment by disk91** [comment]
This has been fixed, you can git pull and compile.
Thank you for reporting this issue.
